### ISSUE TITLE
Close without saving link actually saves changes rather than cancelling the changes

### ISSUE THREAD

**Issue by CAMPSMITH** [uPortal-Project/SimpleContentPortlet#340]
The close without saving link at the bottom of the editor for the SimpleContentPortlet saves and commits changes rather than  cancelling / discarding the changes.  

We are using uPortal 5.11, we also experienced this in 5.9

Steps to reproduce:
1. Ensure you are privileged to configure a SimpleContentManagement portlet
2. Select the configure option in the Options menu of the portlet to edit
3. Change the content in the content editor.
4. Scroll to below the portlet and press the Close without Saving (aka cancel) link.
5. Portlet content commits the changes despite the Close without saving link

The link implies that the behavior should have been to cancel the edit and revert the portlet content to what it was prior to the user entering in the editing mode.

**Comment by groybal** [comment]
This issue has been resolved with PR:  https://github.com/uPortal-Project/SimpleContentPortlet/pull/458
